### ISSUE TITLE
模型选择没生效，GPT4和GPT3.5选择失效

### ISSUE THREAD

**Issue by claywong** [lukenc/GPT4_lll#1]
模型选择没生效，GPT4和GPT3.5选择失效
![image](https://github.com/lukenc/GPT4_lll/assets/222770/00893982-95ea-4fdb-ac4c-532db5be3923)
另外我提供的key并没有开通GPT4

**Comment by lukenc** [comment]
注意到了，已经做了对应的修改。
感谢提出宝贵的建议。 
@claywong
